### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by roshniupadhyay** [shalinshukla/testingarbeltsprint1#5]

**Comment by shalinshukla** [comment]
Work On slider Component

**Comment by shalinshukla** [comment]
Header Main menu integration is done Please take pull and drush CIM

**Comment by shalinshukla** [comment]
@roshniupadhyay  please confirm overlay design and width :nerd_face:

**Comment by roshniupadhyay** [comment]
I am not able to see any design

![arhome](https://user-images.githubusercontent.com/39239989/40077165-6b10e040-589e-11e8-9be5-bad0202bb794.png)

**Comment by shalinshukla** [comment]
The new theme is added I am adding my DB Please import the latest one to see the reflections
But facing some js error 
The design is integrated with menu Slider and one section please review

**Comment by shalinshukla** [comment]
[Uploading 1.png…]()
[Uploading 2.png…]()

**Comment by shalinshukla** [comment]
Home page is done except footer

**Comment by shalinshukla** [comment]
Last Footer Will be done later
